# NTRIP Atlas Service Definition Schema v1.0
#
# This schema defines the structure for NTRIP service definitions
# that get compiled into the service database at build time.

service:
  required: true
  type: object
  properties:
    # Service identification
    id:
      required: true
      type: string
      description: "Unique service identifier for credential storage"
      pattern: "^[a-z0-9_-]+$"
      maxlength: 32

    provider:
      required: true
      type: string
      description: "Organization providing the service"
      maxlength: 64

    country:
      required: true
      type: string
      description: "ISO 3166-1 alpha-2 country code"
      pattern: "^[A-Z]{2}$"

    # Network endpoints
    endpoints:
      required: true
      type: array
      items:
        type: object
        properties:
          hostname:
            required: true
            type: string
            maxlength: 31  # ntrip_service_compact_t limit
          port:
            required: true
            type: integer
            minimum: 1
            maximum: 65535
          ssl:
            type: boolean
            default: false

    # Geographic coverage
    coverage:
      required: true
      type: object
      properties:
        # Simple bounding box (for basic coverage estimation)
        bounding_box:
          required: true
          type: object
          properties:
            lat_min:
              required: true
              type: number
              minimum: -90.0
              maximum: 90.0
            lat_max:
              required: true
              type: number
              minimum: -90.0
              maximum: 90.0
            lon_min:
              required: true
              type: number
              minimum: -180.0
              maximum: 180.0
            lon_max:
              required: true
              type: number
              minimum: -180.0
              maximum: 180.0

        # Hierarchical coverage levels
        hierarchical:
          type: object
          description: "Multi-level coverage areas for efficient bitmap storage"
          properties:
            # Coverage quality by level (1-5, optional means not covered at this level)
            continental:
              type: integer
              minimum: 1
              maximum: 5
              description: "Coverage quality at continental level (Level 0)"
            regional:
              type: integer
              minimum: 1
              maximum: 5
              description: "Coverage quality at regional level (Level 1)"
            national:
              type: integer
              minimum: 1
              maximum: 5
              description: "Coverage quality at national level (Level 2)"
            state:
              type: integer
              minimum: 1
              maximum: 5
              description: "Coverage quality at state/province level (Level 3)"
            local:
              type: integer
              minimum: 1
              maximum: 5
              description: "Coverage quality at local level (Level 4)"

            # Override specific geographic areas with custom coverage
            custom_areas:
              type: array
              description: "Custom coverage areas for irregular service boundaries"
              items:
                type: object
                properties:
                  name:
                    type: string
                    description: "Human-readable area name"
                  bounding_box:
                    type: object
                    properties:
                      lat_min: { type: number, minimum: -90.0, maximum: 90.0 }
                      lat_max: { type: number, minimum: -90.0, maximum: 90.0 }
                      lon_min: { type: number, minimum: -180.0, maximum: 180.0 }
                      lon_max: { type: number, minimum: -180.0, maximum: 180.0 }
                  quality:
                    type: integer
                    minimum: 1
                    maximum: 5

    # Authentication requirements
    authentication:
      required: true
      type: object
      properties:
        method:
          required: true
          type: string
          enum: ["none", "basic", "digest"]
        required:
          required: true
          type: boolean
        registration_required:
          type: boolean
          default: false
        registration_url:
          type: string
          description: "URL for service registration if required"

    # Service quality metrics
    quality:
      required: true
      type: object
      properties:
        reliability_rating:
          required: true
          type: integer
          minimum: 1
          maximum: 5
          description: "1=experimental, 2=intermittent, 3=community, 4=commercial, 5=government"
        accuracy_rating:
          required: true
          type: integer
          minimum: 1
          maximum: 5
          description: "RTK accuracy and precision rating"
        network_type:
          required: true
          type: string
          enum: ["government", "commercial", "community"]

    # Optional metadata
    metadata:
      type: object
      properties:
        description:
          type: string
          maxlength: 256
        stations:
          type: integer
          description: "Number of reference stations"
        coverage_area:
          type: string
          description: "Human-readable coverage description"
        last_verified:
          type: string
          format: "date"
          description: "Last verification date (YYYY-MM-DD)"
        ntrip_version:
          type: string
          enum: ["1.0", "2.0", "mixed"]
          description: "NTRIP protocol version supported"
        rtcm_formats:
          type: array
          items:
            type: string
          description: "Supported RTCM message formats (e.g., RTCM 3.3, RTCM 3.2)"
        constellations:
          type: array
          items:
            type: string
            enum: ["GPS", "GLONASS", "Galileo", "BeiDou", "QZSS", "NavIC", "SBAS"]
          description: "Supported GNSS constellations"
        primary_crs:
          type: string
          description: "Primary coordinate reference system (e.g., EPSG:4326, NAD83(2011))"
        coordinate_systems:
          type: array
          items:
            type: string
          description: "Additional supported coordinate systems for professional use"